### ISSUE TITLE
Add support for Render.com

### ISSUE THREAD

**Issue by danielmichaels** [ryanto/next-deploy-notifications#2]
Hey there,

This is a great library, thanks a lot for putting this together.

Is it possible to add support for [Render.com](https://render.com)?

The two environment variables that would make this supported out of the box (like vercel) are `RENDER_GIT_COMMIT` and `RENDER`

See the [docs](https://render.com/docs/environment-variables).

My first impressions would be to create:

```js
let isRender: IsEnvironment = () => !!process.env.RENDER;
let getRenderVersion: GetVersion = () => `${process.env.RENDER_GIT_COMMIT}`;
```
and then reference them in the handler like so:

```js
let makeRouteHandler = (options: Options = {}): Handler => {
  let route: NextRouteHandler = async (req, res) => {
    let findVersion = options.version
      ? options.version()
      : isVercel()
      ? getVercelVersion()
      : isRender() # untested
      ? getRenderVersion() # untested
      : isGit()
      ? getGitVersion()
      : getUnknownVersion();
    let version = await Promise.resolve(findVersion);
    res.status(200).json({ version });
  };
```

I am happy to open a PR for this if it's a viable option. 

Cheers

**Comment by ryanto** [comment]
Awesome, this is perfect!

I'll absolutely merge the PR if you want to open it

**Comment by danielmichaels** [comment]
I've created a PR for this #3 

Cheers!
